import {useMemo,useState} from 'react';
import {LayoutDashboard,FolderKanban,ClipboardList,FlaskConical,TriangleAlert,Truck,LogOut,Search,Plus,Bell,ChevronRight,CheckCircle2,Clock3,XCircle,ShieldCheck,Menu,X} from 'lucide-react';
import type {Project} from './types';
import {projects,requirements,tests,tasks,risks} from './data';
import {isCloud} from './supabase';

const nav=[['dashboard','总览',LayoutDashboard],['projects','项目',FolderKanban],['requirements','需求',ClipboardList],['validation','技术验证',FlaskConical],['risks','风险',TriangleAlert],['handover','移交',Truck]] as const;
const color=(v:string)=>v==='严重'||v==='FAIL'?'red':v==='高'||v==='BLOCKED'||v==='Open'?'orange':v==='中'||v==='进行中'?'yellow':'green';
function Pill({children}:{children:string}){return <span className={'pill '+color(children)}>{children}</span>}
function Stat({label,value,sub,tone='blue'}:{label:string;value:number|string;sub:string;tone?:string}){return <div className={'stat '+tone}><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div><div className="spark"><i/><i/><i/><i/><i/></div></div>}
function Sidebar({page,setPage,open,setOpen}:{page:string;setPage:(p:string)=>void;open:boolean;setOpen:(v:boolean)=>void}){return <aside className={open?'open':''}><div className="brand"><div className="mark">H</div><div><b>AMR PROJECT</b><span>MANAGEMENT SYSTEM</span></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([id,name,I])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><I size={19}/>{name}</button>)}</nav><div className="sidefoot"><div className="avatar">LU</div><div><b>Lucas</b><span>系统管理员</span></div><LogOut size={18}/></div></aside>}
function ProjectTable({onOpen,rows=projects}:{onOpen:(p:Project)=>void;rows?:Project[]}){return <div className="card table"><div className="cardhead"><div><h3>项目列表</h3><p>所有 AMR 项目的实时状态</p></div><button className="outline">查看全部 <ChevronRight size={16}/></button></div><div className="scroll"><table><thead><tr><th>项目</th><th>客户</th><th>项目经理</th><th>阶段</th><th>进度</th><th>风险</th><th></th></tr></thead><tbody>{rows.map(p=><tr key={p.id} onClick={()=>onOpen(p)}><td><b>{p.name}</b><span>{p.description}</span></td><td>{p.customer}</td><td><div className="person"><i>{p.pm[0]}</i>{p.pm}</div></td><td><Pill>{p.status}</Pill></td><td><div className="progress"><span><i style={{width:p.progress+'%'}}/></span><b>{p.progress}%</b></div></td><td><Pill>{p.risk}</Pill></td><td><ChevronRight size={17}/></td></tr>)}</tbody></table></div></div>}
function Dashboard({openProject}:{openProject:(p:Project)=>void}){return <><div className="title"><div><h1>项目总览</h1><p>上午好，Lucas。以下是欧洲 AMR 项目的最新情况。</p></div><button className="primary"><Plus size={18}/> 新建项目</button></div><section className="stats"><Stat label="项目总数" value={18} sub="较上月 +2"/><Stat label="进行中" value={12} sub="67% 的项目" tone="cyan"/><Stat label="风险项目" value={3} sub="1 个严重风险" tone="orange"/><Stat label="即将交付" value={4} sub="未来 30 天" tone="purple"/></section><section className="grid"><ProjectTable onOpen={openProject}/><div className="card weekly"><div className="cardhead"><div><h3>本周任务</h3><p>9月7日 — 9月13日</p></div><b>5 / 12</b></div>{tasks.map((t,i)=><div className="task" key={t.id}><button className={i===0?'done':''}>{i===0&&<CheckCircle2 size={18}/>}</button><div><b>{t.title}</b><span>{t.owner} · {t.date}</span></div><Pill>{t.status}</Pill></div>)}</div></section><section className="lower"><div className="card riskcard"><div className="cardhead"><div><h3>重点风险</h3><p>需要优先处理的项目风险</p></div><span className="count">3</span></div>{risks.map(r=><div className="riskrow" key={r.id}><span className={'dot '+color(r.priority||'')}/><div><b>{r.title}</b><span>{projects.find(p=>p.id===r.projectId)?.name} · Owner: {r.owner}</span></div><Pill>{r.priority!}</Pill></div>)}</div><div className="card health"><div className="cardhead"><div><h3>项目健康度</h3><p>按当前项目状态统计</p></div></div><div className="donut"><div><b>78%</b><span>健康</span></div></div><ul><li><i className="green"/>正常 <b>11</b></li><li><i className="yellow"/>需关注 <b>4</b></li><li><i className="red"/>高风险 <b>3</b></li></ul></div></section></>}
function Detail({p,back}:{p:Project;back:()=>void}){const [tab,setTab]=useState('概览');const tabs=['概览','需求','技术验证','任务','风险','现场交付','项目移交'];return <><button className="back" onClick={back}>← 返回项目</button><div className="projecthero"><div><span className="eyebrow">{p.customer} / AMR PROJECT</span><h1>{p.name}</h1><p>{p.description}</p></div><div><Pill>{p.status}</Pill><strong>{p.progress}%</strong><span>总体进度</span></div></div><div className="tabs">{tabs.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==='概览'&&<section className="detailgrid"><div className="card info"><h3>项目基本信息</h3><dl><div><dt>项目经理</dt><dd>{p.pm}</dd></div><div><dt>技术负责人</dt><dd>{p.engineer}</dd></div><div><dt>开始日期</dt><dd>{p.start}</dd></div><div><dt>计划交付</dt><dd>{p.delivery}</dd></div></dl></div><div className="card"><h3>交付阶段</h3><div className="timeline">{['需求确认','技术验证','现场实施','FAT / SAT','培训与移交'].map((x,i)=><div className={i<3?'done':''} key={x}><i>{i<3?'✓':i+1}</i><span>{x}<small>{i<2?'已完成':i===2?'进行中':'待开始'}</small></span></div>)}</div></div></section>}{tab==='需求'&&<List title="需求追踪" items={requirements}/>} {tab==='技术验证'&&<List title="技术验证测试" items={tests}/>} {tab==='任务'&&<List title="项目任务" items={tasks}/>} {tab==='风险'&&<List title="风险登记册" items={risks.filter(x=>x.projectId===p.id)}/>} {tab==='现场交付'&&<Delivery/>}{tab==='项目移交'&&<Handover/>}</>}
function List({title,items}:{title:string;items:typeof tasks}){return <div className="card list"><div className="cardhead"><div><h3>{title}</h3><p>共 {items.length} 项</p></div><button className="primary"><Plus size={17}/> 新增</button></div>{items.map(x=><div className="listrow" key={x.id}><code>{x.id}</code><div><b>{x.title}</b><span>{x.detail||('截止 '+x.date)}</span></div><span>{x.owner}</span>{x.priority&&<Pill>{x.priority}</Pill>}<Pill>{x.status}</Pill></div>)}</div>}
function Delivery(){return <div className="card delivery"><h3>现场实施进度</h3>{['设备到货','Robot Installation','RCS Installation','Map Creation','Robot Commissioning','WCS Integration','PLC Integration','FAT','SAT','Training','Go Live'].map((x,i)=><div key={x}><i className={i<6?'done':''}>{i<6?'✓':i+1}</i><b>{x}</b><span>{i<6?'已完成':i===6?'进行中':'待开始'}</span><small>{i<6?'2026-09-0'+(i+1):'计划 2026-09-'+(10+i)}</small></div>)}</div>}
function Handover(){return <div className="handover">{['Documentation','Testing','Training','Final'].map((g,gi)=><div className="card" key={g}><h3>{g}</h3>{(gi===0?['Project Specification','Network Architecture','Robot Configuration','RCS Configuration']:gi===1?['FAT','SAT','Performance Test','Safety Test']:gi===2?['Customer Training','Maintenance Training']:['Customer Acceptance','As-built Documentation','Backup','Handover']).map((x,i)=><label key={x}><input type="checkbox" defaultChecked={gi<2&&i<2}/><span>{x}</span></label>)}</div>)}</div>}
function App(){const [page,setPage]=useState('dashboard');const [selected,setSelected]=useState<Project|null>(null);const [query,setQuery]=useState('');const [menu,setMenu]=useState(false);const rows=useMemo(()=>projects.filter(p=>(p.name+p.customer+p.pm).toLowerCase().includes(query.toLowerCase())),[query]);const open=(p:Project)=>{setSelected(p);setPage('detail')};return <div className="app"><Sidebar page={page} setPage={(x)=>{setPage(x);setSelected(null)}} open={menu} setOpen={setMenu}/><main><header><button className="menubtn" onClick={()=>setMenu(true)}><Menu/></button><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索项目、客户或负责人…"/></div><div className="cloud"><i className={isCloud?'on':''}/>{isCloud?'云端已连接':'演示模式'}</div><button className="icon"><Bell size={19}/><i/></button><div className="avatar">LU</div></header><div className="content">{selected?<Detail p={selected} back={()=>{setSelected(null);setPage('projects')}}/>:page==='dashboard'?<Dashboard openProject={open}/>:page==='projects'?<><div className="title"><div><h1>项目</h1><p>管理全部 AMR 项目生命周期</p></div><button className="primary"><Plus/>新建项目</button></div><ProjectTable rows={rows} onOpen={open}/></>:<Module page={page}/>}</div></main></div>}
function Module({page}:{page:string}){if(page==='requirements')return <><div className="title"><div><h1>需求管理</h1><p>从客户需求到技术方案的完整追踪</p></div></div><List title="全部需求" items={requirements}/></>;if(page==='validation')return <><div className="title"><div><h1>技术验证</h1><p>测试用例、执行结果与证据管理</p></div></div><section className="stats"><Stat label="测试用例" value={42} sub="全部项目"/><Stat label="PASS" value={37} sub="88% 通过率" tone="cyan"/><Stat label="FAIL" value={3} sub="需要修复" tone="orange"/><Stat label="BLOCKED" value={2} sub="等待条件" tone="purple"/></section><List title="测试用例" items={tests}/></>;if(page==='risks')return <><div className="title"><div><h1>风险管理</h1><p>识别、跟踪并关闭项目风险</p></div></div><List title="风险登记册" items={risks}/></>;return <><div className="title"><div><h1>项目移交</h1><p>确保文档、测试、培训和最终交付完整闭环</p></div></div><Handover/></>}
export default App;
